### ISSUE TITLE
公式に合わせる(近くする)

### ISSUE THREAD

**Issue by Takesikaityo** [StarrySky-PE/StarrySky#8]
バーションとかも公式に合わせてみるのもいいと思います。
(codenameは別)
string(lang系も)近くするように心がけています

**Comment by towa0131** [comment]
Versionなどは大規模アップデートなどであげるようにしています。
APIなどは出来るだけ公式にあわせるとして、バージョンなどは独自のものにしていくつもりです。

**Comment by Takesikaityo** [comment]
ok
