### ISSUE TITLE
BigBrother

### ISSUE THREAD

**Issue by ghost** [StarrySky-PE/StarrySky#9]
I tried your BigBrother version with your StarrySky software but it does not work.

**Comment by lolmanz0** [comment]
![image](https://cloud.githubusercontent.com/assets/25885263/23703377/e7e99840-03ff-11e7-860d-1b0b2c4f91a3.png)

**Comment by lolmanz0** [comment]
![image](https://cloud.githubusercontent.com/assets/25885263/23703478/7194279a-0400-11e7-9da4-2f9376bc9d30.png)

**Comment by lolmanz0** [comment]
![image](https://cloud.githubusercontent.com/assets/25885263/23703545/bdb6c7ea-0400-11e7-8566-4f53a848b33c.png)

**Comment by lolmanz0** [comment]
![image](https://cloud.githubusercontent.com/assets/25885263/23703584/f7666b94-0400-11e7-9a93-229f409bc0b5.png)
